FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    kali-linux-headless \
    nmap \
    net-tools \
    iputils-ping \
    dnsutils \
    curl \
    wget \
    git \
    python3 \
    python3-pip \
    vim \
    nano \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/lab

CMD ["/bin/bash"]